---
name: PRBuild
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, x64]
        os: [win, linux]
    steps:
      - name: Get ASBDDS
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup packages
        run: |
            sudo apt update
            sudo apt install -y apt-transport-https
            sudo apt install -y dotnet-sdk-6.0
      - name: Build ASBDDS
        run: |
            dotnet publish ASBDDS --self-contained -c Release -r ${{ matrix.os }}-${{ matrix.arch }} -o ./build/${{ matrix.os }}-${{ matrix.arch }}
            tar -zcvf asbdds-${{ matrix.os }}-${{ matrix.arch }}.tar.gz ./build/${{ matrix.os }}-${{ matrix.arch }}
      - name: Upload ASBDDS
        uses: actions/upload-artifact@v2
        with:
          name: asbdds-${{ matrix.os }}-${{ matrix.arch }}
          path: asbdds-${{ matrix.os }}-${{ matrix.arch }}.tar.gz